
default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
        sh "flutter clean"
        sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
        firebase_app_distribution(
        app: "1:413795537013:android:7887e98bb1d071f357a83c",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "ahmedalghitany@std.mans.edu.eg",
        release_notes: "First Fastlane Firebase Distribution!"
      )
  end

end
